# Generated by Django 5.2.4 on 2026-09-07 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTrackingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('device_model', models.CharField(blank=True, default='', max_length=255)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('consent_given', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_tracking_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number involved in the call.', max_length=20)),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('missed', 'Missed')], db_index=True, max_length=10)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Call duration in seconds.')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the call occurred on the device.')),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='When this record was synced to the server.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='idx_user_timestamp')],
                'constraints': [models.UniqueConstraint(fields=('user', 'phone_number', 'timestamp'), name='unique_call_log_entry')],
            },
        ),
        migrations.CreateModel(
            name='CallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The date these statistics cover.')),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total call duration in seconds for this date.')),
                ('calls_by_type', models.JSONField(default=dict, help_text='Breakdown by call type, e.g. {"incoming": 5, "outgoing": 3, "missed": 1}')),
                ('top_numbers', models.JSONField(default=list, help_text='Top contacted numbers, e.g. [{"number": "+91...", "count": 10}, ...]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_stats',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_stats')],
            },
        ),
    ]
