# Generated by Django 5.2.4 on 2026-09-07 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_tracking', '0001_initial'),
        ('customer_dashboard', '0011_crosssellingremark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Matched customer based on normalized phone number.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customer_dashboard.customer'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='E.164 normalized phone number for customer matching.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['normalized_phone'], name='idx_normalized_phone'),
        ),
    ]
