# Generated by Django 6.1 on 2026-08-31 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_dashboard', '0011_crosssellingremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Meta – Diwali Campaign 2025'", max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('META', 'Meta (Facebook / Instagram)'), ('INDIAMART', 'IndiaMart'), ('JUSTDIAL', 'Just Dial'), ('REFERRAL', 'Referral'), ('WALK_IN', 'Walk-in'), ('WEBSITE', 'Website'), ('COLD_CALL', 'Cold Call'), ('EXHIBITION', 'Exhibition / Trade Show'), ('WHATSAPP', 'WhatsApp Campaign'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('campaign_meta', models.JSONField(blank=True, default=dict, help_text='Any extra fields: campaign_id, ad_set, platform, etc.')),
                ('cost_per_lead', models.DecimalField(blank=True, decimal_places=2, help_text='Average CPL for this source/campaign', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for Kanban column header', max_length=7)),
                ('is_closed', models.BooleanField(default=False, help_text='Mark as true for Won / Lost / Junk terminal stages')),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NOT_INTERESTED', 'Not Interested'), ('PRICE_HIGH', 'Price Too High'), ('NO_ANSWER', 'Call Not Picked'), ('BUSY', 'Customer Busy / Asked to Call Later'), ('STOCK_NA', 'Stock Not Available'), ('ALREADY_PURCHASED', 'Already Purchased Elsewhere'), ('NEED_TIME', 'Need Time to Decide'), ('WRONG_NUMBER', 'Wrong Number'), ('LANGUAGE_BARRIER', 'Language Barrier'), ('POSITIVE_INTEREST', 'Positive Interest'), ('REQUESTED_CALLBACK', 'Requested Callback'), ('QUOTATION_SENT', 'Quotation Sent'), ('ORDER_PLACED', 'Order Placed'), ('OTHER', 'Other')], max_length=30, unique=True)),
                ('label', models.CharField(help_text='Human-readable label shown in dropdowns', max_length=200)),
                ('requires_price_data', models.BooleanField(default=False, help_text='True for PRICE_HIGH – asks quoted/requested price+product')),
                ('requires_why', models.BooleanField(default=False, help_text='True for NOT_INTERESTED – asks why')),
                ('is_positive', models.BooleanField(default=False, help_text='True for outcomes that move lead forward')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='RemarkRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('RELEVANT', 'Relevant'), ('SPAM', 'Spam / Junk'), ('FOLLOWUP', 'Follow-up Required'), ('ESCALATE', 'Escalate to Manager')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Remark Relevances',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit from LeadSource.cost_per_lead', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost'), ('JUNK', 'Junk / Spam'), ('ON_HOLD', 'On Hold')], default='OPEN', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Any source-specific fields (e.g. IndiaMart query, product interest)')),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customer_dashboard.salesperson')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadstage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('followup_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_followups', to='customer_dashboard.salesperson')),
            ],
            options={
                'ordering': ['followup_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_discussed', models.CharField(blank=True, max_length=255, null=True)),
                ('not_interested_why', models.CharField(blank=True, choices=[('NO_NEED', 'No current need'), ('COMPETITOR', 'Using a competitor'), ('BAD_EXPERIENCE', 'Past bad experience'), ('TOO_SMALL', 'Business too small'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_remarks', to='leads.lead')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_remarks', to='customer_dashboard.salesperson')),
                ('reason_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks', to='leads.reasoncode')),
                ('relevance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks', to='leads.remarkrelevance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('NOT_PICKED', 'Not Picked'), ('BUSY', 'Busy'), ('SWITCHED_OFF', 'Switched Off'), ('WRONG_NUMBER', 'Wrong Number'), ('VOICEMAIL', 'Voicemail')], default='CONNECTED', max_length=20)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Call duration in minutes', null=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_made', to='customer_dashboard.salesperson')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead')),
                ('remark', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call', to='leads.leadremark')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_dashboard.salesperson')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadstage')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadstage')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
    ]
